name = "node-template"
version = "0.1.0"
description = "Template for Stencila plugin written in Node.js"
home = "https://github.com/stencila/plugin-node-template"
install = "https://github.com/stencila/plugin-node-template"
runtime = "node>=16"
transports = ["stdio", "http"]
command = "npx run"

[[kernels]]
name = "echo-node"

[[assistants]]
name = "stencila/echo-node"
title = "Node.js Echo Assistant"
content-format = "markdown"
system-prompt = true
models = false
